sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before-install:
  - openssl aes-256-cbc -K $encrypted_fe86bdf4cc96_key -iv $encrypted_fe86bdf4cc96_iv -in multi-docker-k8s.json.enc -out multi-docker-k8s.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-docker-k8s.json
  - gcloud config set project multi-docker-k8s-284113
  - gcloud config set compute/zone us-central1-c  
  - gcloud container clusters get-credentials cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
