apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: candidwork-co-tls
spec:
  secretName: candidwork-co
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: candidwork.co
  dnsNames:
   - candidwork.co
   - www.candidwork.co
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - candidwork.co
          - www.candidwork.co